package edu.saddleback.cs4b.Backend;


public enum MessageType
{
    ACTIVE_USER_MESSAGE,
    DISCONnECT_MESSAGE,
    SIGN_OUT_MESSAGE,
    SIGN_IN_MESSAGE,
    DENIAL_MESSAGE,
    AUTHORIZATION_MESSAGE,
    SUCCESSFUL_REGISTRATION_MESSAGE,
    INVALID_REGISTRATION_MESSAGE,
    PACHES_MESSAGE
}

